### ISSUE TITLE
ValueError: No such group: africa_30/2021-11--P1M/+0178/+0097

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/ndvi-anomalies#30]
W
  da = self.__array_wrap__(f(self.variable.data, *args, **kwargs))
Traceback (most recent call last):
  File "/usr/local/bin/odc-stats", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/_cli_run.py", line 188, in run
    for result in result_stream:
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/proc.py", line 186, in _run
    for task in tasks:
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/tasks.py", line 577, in stream_from_sqs
    yield self.load_task(tidx, product, source=token, ds_filters=ds_filters)
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/tasks.py", line 527, in load_task
    dss = self.datasets(tile_index)
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/tasks.py", line 514, in datasets
    return tuple(
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/tasks.py", line 514, in <genexpr>
    return tuple(
  File "/usr/local/lib/python3.8/dist-packages/odc/dscache/_dscache.py", line 280, in stream_group
    for _, v in self._db.stream_group(group_name):
  File "/usr/local/lib/python3.8/dist-packages/odc/dscache/_jsoncache.py", line 399, in stream_group
    raise ValueError(f"No such group: {group_name}")
ValueError: No such group: africa_30/2021-11--P1M/+0178/+0097

**Comment by alexgleith** [comment]
Error is above. Context is that I have pushed messages from 3 different DBs to an SQS queue and I think that Stats might not be checking the local DB is the one that's in the S3 URI.
