### ISSUE TITLE
ValueError: Failed to group data. Are you grouping by a variable that is all NaN?

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/ndvi-anomalies#32]
Traceback (most recent call last):
  File "/usr/local/bin/odc-stats", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/_cli_run.py", line 187, in run
    for result in result_stream:
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/proc.py", line 206, in _run
    ds = proc.reduce(proc.input_data(task.datasets, task.geobox))
  File "/usr/local/lib/python3.8/dist-packages/ndvi_tools/ndvi_anomaly_plugin.py", line 179, in input_data
    ls89 = load_with_native_transform(
  File "/usr/local/lib/python3.8/dist-packages/odc/algo/io.py", line 176, in load_with_native_transform
    for srcs in _split_by_grid(sources)
  File "/usr/local/lib/python3.8/dist-packages/odc/algo/io.py", line 63, in _split_by_grid
    return [extract(ii) for ii in xx.groupby(xx.grid).groups.values()]
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/common.py", line 721, in groupby
    return self._groupby_cls(
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/groupby.py", line 385, in __init__
    raise ValueError(
ValueError: Failed to group data. Are you grouping by a variable that is all NaN?

**Comment by alexgleith** [comment]
`INFO - Starting processing of x178/y088/2021-08--P1M`

Traceback (most recent call last):
  File "/usr/local/bin/odc-stats", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/_cli_run.py", line 187, in run
    for result in result_stream:
  File "/usr/local/lib/python3.8/dist-packages/odc/stats/proc.py", line 206, in _run
    ds = proc.reduce(proc.input_data(task.datasets, task.geobox))
  File "/usr/local/lib/python3.8/dist-packages/ndvi_tools/ndvi_anomaly_plugin.py", line 179, in input_data
    ls89 = load_with_native_transform(
  File "/usr/local/lib/python3.8/dist-packages/odc/algo/io.py", line 176, in load_with_native_transform
    for srcs in _split_by_grid(sources)
  File "/usr/local/lib/python3.8/dist-packages/odc/algo/io.py", line 63, in _split_by_grid
    return [extract(ii) for ii in xx.groupby(xx.grid).groups.values()]
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/common.py", line 721, in groupby
    return self._groupby_cls(
  File "/usr/local/lib/python3.8/dist-packages/xarray/core/groupby.py", line 385, in __init__
    raise ValueError(
ValueError: Failed to group data. Are you grouping by a variable that is all NaN?

**Comment by alexgleith** [comment]
Also `x179/y084/2021-09--P1M`
